hyperskill_project:
  id: 260
  ide_files: https://stepik.org/media/attachments/lesson/738351/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Wed, 21 Sep 2022 17:07:37 UTC"
stages:
- id: 1316
  step: 20315
  is_completed: true
- id: 1317
  step: 20316
  is_completed: true
- id: 1318
  step: 20317
  is_completed: true
- id: 1319
  step: 20318
  is_completed: true
- id: 1320
  step: 20319
  is_completed: true
topics:
  0:
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  1:
  - title: Types and variables
    theory_id: 3518
  - title: Comments
    theory_id: 3520
  - title: Scanning the input
    theory_id: 9055
  - title: Characters
    theory_id: 3514
  - title: String
    theory_id: 3523
  - title: Coding style conventions
    theory_id: 12411
  - title: Naming variables
    theory_id: 3513
  2:
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: "Write, compile, and run"
    theory_id: 3739
  - title: "JVM, JRE, and JDK"
    theory_id: 3499
  - title: Sizes and ranges
    theory_id: 3532
  - title: Type casting
    theory_id: 3510
  - title: Calling a method
    theory_id: 10973
  - title: The while and do-while loops
    theory_id: 3498
  - title: The for-loop
    theory_id: 3505
  - title: Branching statements
    theory_id: 3507
  - title: Declaring a method
    theory_id: 10982
  - title: The main method
    theory_id: 3489
  - title: Switch statement
    theory_id: 3504
  - title: Functional decomposition
    theory_id: 10570
  - title: Running programs on your computer
    theory_id: 3746
  - title: Primitive and reference types
    theory_id: 5035
  - title: Arithmetic operations
    theory_id: 3519
  - title: Integer types and operations
    theory_id: 3565
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Conditional statement
    theory_id: 3503
  - title: What is an exception
    theory_id: 3497
  - title: Hierarchy of exceptions
    theory_id: 3570
  - title: Exception handling
    theory_id: 3552
  - title: What is a bug
    theory_id: 5504
  - title: Files
    theory_id: 3635
  - title: Reading files
    theory_id: 3636
  - title: Introduction to logging
    theory_id: 5538
  - title: Debugging techniques
    theory_id: 13775
  - title: Defining classes
    theory_id: 3618
  - title: Constructor
    theory_id: 3535
  - title: Instance methods
    theory_id: 3495
  - title: Access modifiers
    theory_id: 3589
  - title: Getters and setters
    theory_id: 3599
  - title: Inheritance
    theory_id: 3583
  - title: The keyword super
    theory_id: 3588
  - title: Objects
    theory_id: 4727
  3:
  - title: Computer algorithms
    theory_id: 16547
  - title: The big O notation
    theory_id: 16699
  - title: "Best, average and worst cases"
    theory_id: 20084
  - title: Data structures
    theory_id: 16927
  - title: Pseudocode
    theory_id: 15090
  - title: Pseudocode basics
    theory_id: 19510
  - title: Complex constructions in pseudocode
    theory_id: 20922
  - title: Fixed-size array
    theory_id: 20078
  - title: Dynamic array
    theory_id: 5357
  - title: Array
    theory_id: 3511
  - title: Iterating over arrays
    theory_id: 3602
  - title: Introduction to generic programming
    theory_id: 3492
  - title: What are collections
    theory_id: 3770
  - title: Generics and Object
    theory_id: 3493
  - title: The Collections Framework overview
    theory_id: 3624
  - title: ArrayList
    theory_id: 3567
  - title: The List interface
    theory_id: 3581
  - title: Hiding and overriding
    theory_id: 3572
  - title: Polymorphism
    theory_id: 3587
  - title: Interface
    theory_id: 3615
  - title: Boxing and unboxing
    theory_id: 3595
